FORTH-WORDLIST TASK-WORDLIST 2 SET-ORDER

100 2 NEW-BCHAN CONSTANT MY-BCHAN

: SENDER
  BEGIN
    MY-BCHAN COUNT-BCHAN ." <" (.) ." > " 0 MY-BCHAN SEND-BCHAN
  AGAIN ;

: RECEIVER
  BEGIN
    MY-BCHAN COUNT-BCHAN ." [" (.) ." ] " MY-BCHAN RECV-BCHAN DROP
  AGAIN ;

256 256 256 ' SENDER NEW-TASK CONSTANT SENDER-TASK
256 256 256 ' RECEIVER NEW-TASK CONSTANT RECEIVER-TASK

SENDER-TASK ACTIVATE-TASK RECEIVER-TASK ACTIVATE-TASK

KEY DROP SENDER-TASK DEACTIVATE-TASK RECEIVER-TASK DEACTIVATE-TASK
