FORTH-WORDLIST TASK-WORDLIST 2 SET-ORDER

100 2 NEW-BCHAN CONSTANT MY-BCHAN

: SENDER
  BEGIN
    MY-BCHAN COUNT-BCHAN ." <" (.) ." > " 0 MY-BCHAN SEND-BCHAN
  AGAIN ;

: RECEIVER
  BEGIN
    MY-BCHAN COUNT-BCHAN ." [" (.) ." ] " MY-BCHAN RECV-BCHAN DROP
  AGAIN ;

: ON-PAUSE
  BASE @ >R SINGLE-TASK-IO @ >R
  16 BASE ! TRUE SINGLE-TASK-IO !
  ." *" NEXT-TASK (.) ." * "
  R> SINGLE-TASK-IO ! R> BASE ! ;

256 256 256 ' SENDER NEW-TASK CONSTANT SENDER-TASK
256 256 256 ' RECEIVER NEW-TASK CONSTANT RECEIVER-TASK

: DO-EXAMPLE
  ['] ON-PAUSE 'ON-PAUSE !
  SENDER-TASK ACTIVATE-TASK RECEIVER-TASK ACTIVATE-TASK
  KEY DROP SENDER-TASK DEACTIVATE-TASK RECEIVER-TASK DEACTIVATE-TASK
  0 'ON-PAUSE ! ;

DO-EXAMPLE
