\ Copyright (c) 2019, Travis Bemann
\ All rights reserved.
\ 
\ Redistribution and use in source and binary forms, with or without
\ modification, are permitted provided that the following conditions are met:
\ 
\ 1. Redistributions of source code must retain the above copyright notice,
\    this list of conditions and the following disclaimer.
\ 
\ 2. Redistributions in binary form must reproduce the above copyright notice,
\    this list of conditions and the following disclaimer in the documentation
\    and/or other materials provided with the distribution.
\ 
\ 3. Neither the name of the copyright holder nor the names of its
\    contributors may be used to endorse or promote products derived from
\    this software without specific prior written permission.
\ 
\ THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
\ AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
\ IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
\ ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
\ LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
\ CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
\ SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
\ INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
\ CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
\ ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
\ POSSIBILITY OF SUCH DAMAGE.

FORTH-WORDLIST VECTOR-WORDLIST 2 SET-ORDER

4 256 ALLOT-VECTOR CONSTANT MY-VECTOR

TRUE CONSTANT SUCCESS
FALSE CONSTANT FAILURE

: DUMP-VECTOR ( vector -- )
  >R ." < " 0 BEGIN DUP R@ COUNT-VECTOR < WHILE
    [CHAR] " EMIT HERE 256 ALLOT OVER R@ GET-VECTOR DROP -256 ALLOT
    HERE COUNT TYPE [CHAR] " EMIT SPACE 1 +
  REPEAT
  DROP ." > " R> DROP ;

: PREPARE-BLOCK ( c-addr1 u c-addr2 -- )
  SWAP 255 MIN SWAP 2DUP C! 1 + SWAP MOVE ;

: PUSH-START-ENTRY ( success c-addr u vector -- )
  ROT ROT 2DUP ." pushing-start " [CHAR] " EMIT TYPE [CHAR] " EMIT
  HERE PREPARE-BLOCK HERE 256 ALLOT OVER PUSH-START-VECTOR -256 ALLOT
  SPACE NOT ROT XOR IF ." success " ELSE ." failure " THEN DUMP-VECTOR CR ;

: PUSH-END-ENTRY ( success c-addr u vector -- )
  ROT ROT 2DUP ." pushing-end " [CHAR] " EMIT TYPE [CHAR] " EMIT
  HERE PREPARE-BLOCK HERE 256 ALLOT OVER PUSH-END-VECTOR -256 ALLOT
  SPACE NOT ROT XOR IF ." success " ELSE ." failure " THEN DUMP-VECTOR CR ;

: POP-START-ENTRY ( success vector -- )
  ." popping-start " HERE 256 ALLOT OVER POP-START-VECTOR -256 ALLOT
  DUP IF [CHAR] " EMIT HERE COUNT TYPE [CHAR] " EMIT SPACE THEN
  NOT ROT XOR IF ." success " ELSE ." failure " THEN DUMP-VECTOR CR ;
  
: POP-END-ENTRY ( success vector -- )
  ." popping-end " HERE 256 ALLOT OVER POP-END-VECTOR -256 ALLOT
  DUP IF [CHAR] " EMIT HERE COUNT TYPE [CHAR] " EMIT SPACE THEN
  NOT ROT XOR IF ." success " ELSE ." failure " THEN DUMP-VECTOR CR ;

: PEEK-START-ENTRY ( success vector -- )
  ." peeking-start " HERE 256 ALLOT OVER PEEK-START-VECTOR -256 ALLOT
  DUP IF [CHAR] " EMIT HERE COUNT TYPE [CHAR] " EMIT SPACE THEN
  NOT ROT XOR IF ." success " ELSE ." failure " THEN DUMP-VECTOR CR ;
  
: PEEK-END-ENTRY ( success vector -- )
  ." peeking-end " HERE 256 ALLOT OVER PEEK-END-VECTOR -256 ALLOT
  DUP IF [CHAR] " EMIT HERE COUNT TYPE [CHAR] " EMIT SPACE THEN
  NOT ROT XOR IF ." success " ELSE ." failure " THEN DUMP-VECTOR CR ;

: VECTOR-TEST ( -- )
  SUCCESS S" foo" MY-VECTOR PUSH-START-ENTRY
  SUCCESS S" bar" MY-VECTOR PUSH-END-ENTRY
  SUCCESS S" baz" MY-VECTOR PUSH-START-ENTRY
  SUCCESS S" qux" MY-VECTOR PUSH-END-ENTRY
  FAILURE S" foobar" MY-VECTOR PUSH-START-ENTRY
  FAILURE S" foobaz" MY-VECTOR PUSH-END-ENTRY
  SUCCESS MY-VECTOR PEEK-START-ENTRY
  SUCCESS MY-VECTOR PEEK-END-ENTRY
  SUCCESS MY-VECTOR POP-START-ENTRY
  SUCCESS MY-VECTOR POP-END-ENTRY
  SUCCESS MY-VECTOR POP-START-ENTRY
  SUCCESS MY-VECTOR POP-END-ENTRY
  FAILURE MY-VECTOR PEEK-START-ENTRY
  FAILURE MY-VECTOR PEEK-END-ENTRY
  FAILURE MY-VECTOR POP-START-ENTRY
  FAILURE MY-VECTOR POP-END-ENTRY ;

VECTOR-TEST